version: '3'
services:
  config-server:
    build:
      context: config-server
      dockerfile: Dockerfile
    hostname: config-server
    container_name: config-server
    image: config-server:v1
    ports:
      - "8083:8083"
    restart: always
    networks:
      - springcloud
  eureka-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    hostname: eureka-server
    container_name: eureka-server
    image: eureka-server:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
  productos:
    build:
      context: .
      dockerfile: Productos.Dockerfile
    container_name: productos
    ports:
      - "8080:8080"
    image: productos:v1
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
  items:
    build:
      context: .
      dockerfile: Items.Dockerfile
    image: items:v1
    ports:
      - "8007:8007"
    container_name: items
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - productos
  microservicio-usuarios:
    build:
      context: .
      dockerfile: Usuarios.Dockerfile
    image: microservicio-usuarios:v1
    restart: always
    container_name: microservicio-usuarios
    ports:
      - "8088:8088"
    networks:
        - springcloud
    depends_on:
        - config-server
        - eureka-server
  oauth-server:
    build:
      context: .
      dockerfile: Oauth.Dockerfile
    image: servicio-oauth:v1
    container_name: oauth-server
    ports:
      - "8087:8087"
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - microservicio-usuarios
  cloudgateway:
    build:
      context: cloudgateway
      dockerfile: Dockerfile
    image: cloudgateway:v1
    ports:
      - "8090:8090"
    restart: always
    container_name: cloudgateway
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - productos
      - items
      - microservicio-usuarios
      - oauth-server
networks:
  springcloud:
    driver: bridge
