spring:
  cloud:
    gateway:
      routes:
        - id: microservicio-productos
          uri: lb://microservicio-productos
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=Greetings, Welcome
            - SetResponseHeader=Content-Type, text/plain
        - id: microservicio-items
          uri: lb://microservicio-items
          predicates:
            - Path=/api/items/**
            - Method=GET
            - Header=AccessToken, Pass
            #puedes tambien pones Cookie, Query, Time , etc.. en los predicates y tiene q tener eso para q te haga la request
          filters:
            - StripPrefix=2
            - name: Customize
              args:
                headerName: AuthorizationToken
                headerValue: ADMIN
                cookieName: Sorbeticos
                cookieValue: Vainilla
            - AddRequestParameter=greetings, welcome_from_gateway
            - AddRequestHeader=Greetings, Hi!
            - AddResponseHeader=Greetings, Good_Bye
