#TAMBIEN PUEDO METER EL CIRCUITBREAKER AQUI LUEGO DE HABER AGREGADO LA DEPENDENCIA DE REACTOR-RESILENCE4J
#Y PUEDO COPIAR Y PEGAR LA CONFIGURACION DE CIRCUITBREAKER Y TIMELIMITER AQUI Y LUEGO AL MICROSERVICIO QUE QUIERA LE PUEDO
#PONER EL CIRCUITBREAKER SIMPLEMENTE AGRENADO EN EL FILTERS DE ESTE - CircuitBreaker
#PERO SI SE QUIERE QUE ESTE TAMBIEN SEA MEJOR CONFIGURADO Y CON UN FALLBACK METHOD
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      items:
        base-config: defecto
      productos:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 4s
    instances:
      items:
        base-config: defecto
      productos:
        base-config: defecto
spring:
  cloud:
    gateway:
      routes:
        - id: microservicio-productos
          uri: lb://microservicio-productos
          predicates:
            - Path=/api/productos/**
          filters:
#            - name: CircuitBreaker
#              args:
#                name: productos
#                statusCodes: 500
#                fallBackUri: forward:/item/listaitems/n
            - StripPrefix=2
            - AddRequestHeader=Greetings, Welcome
            - SetResponseHeader=Content-Type, text/plain
        - id: microservicio-items
          uri: lb://microservicio-items
          predicates:
            - Path=/api/items/**
            - Method=GET, POST, PUT, DELETE #SI NO PONGO NADA AGARRA TODOS LOS POSIBLES METODOS, ATENCION PORQUE SI DEFINES ALGUNAS SOLO ESOS ADMITIRA Y SI USAS OTRO TE DARA UN 404
            - Header=AccessToken, Pass
            #puedes tambien pones Cookie, Query, Time , etc.. en los predicates y tiene q tener eso para q te haga la request
          filters:
            - StripPrefix=2
            - name: Customize
              args:
                headerName: AuthorizationToken
                headerValue: ADMIN
                cookieName: Sorbeticos
                cookieValue: Vainilla
            - AddRequestParameter=greetings, welcome_from_gateway
            - AddRequestHeader=Greetings, Hi!
            - AddResponseHeader=Greetings, Good_Bye
        - id: microservicio-usuarios
          uri: lb://microservicio-usuarios
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=AccessToken, Pass
        - id: oauth-server
          uri: lb://oauth-server
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=AccessToken, Pass

